AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Exclude:
    - "spec/**/*"
    - "lib/basho/region.rb"
    - "lib/basho/active_record/postal_auto_resolve.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "tasks/**/*"
